version: "3"
services:

    drupal-learn:
      # используем последний стабильный образ nginx
      image: nginx:latest
      # маршрутизируем порты
      ports:
          - "80:80"
          - "443:443"
      # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
      volumes:
          - ./docker/nginx/hosts:/etc/nginx/conf.d
          - ./:/var/www
          - ./docker/nginx/logs:/var/log/nginx
      # nginx должен общаться с php контейнером
      links:
          - drupal-learn-php

    drupal-learn-php:
      # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
      build:
        context: .
        dockerfile: ./docker/images/php/Dockerfile
      # этот образ будет общаться с mysql
      links:
        -  drupal-learn-db
      # монтируем директорию с проектами
      volumes:
        - ./:/var/www

    drupal-learn-db:
      image: wodby/mariadb:10.5-3.9.2
      stop_grace_period: 30s
      environment:
          MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
          MYSQL_PASSWORD: $MYSQL_PASSWORD
          MYSQL_DATABASE: $MYSQL_DATABASE
          MYSQL_USER: $MYSQL_USER
          MYSQL_PASSWORD: $MYSQL_PASSWORD
      volumes:
         - ./docker/mysql/data:/var/lib/mysql # persist data even
      ports:
         - "3306:3306"
    drupal-learn-adminer:
      container_name: "drupal-learn-adminer"
      image: wodby/adminer:4-3.12.1
      environment:
        # For PostgreSQL:
        #      ADMINER_DEFAULT_DB_DRIVER: pgsql
        ADMINER_DEFAULT_DB_HOST: drupal-learn-db
        ADMINER_DEFAULT_DB_NAME: $MYSQL_DATABASE




